#ifndef CORE_RTM_CONFIG_H__INCLUDED
#define CORE_RTM_CONFIG_H__INCLUDED

#define _RTM_CLIENT_T_SIZE 434

#define RTM_HAS_GETENV
#define RTM_HAS_FIO
#define RTM_LOGGING

#endif // CORE_RTM_CONFIG_H__INCLUDED
